{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nickacpt.lightclient",
    "module": "LightClientGradle",
    "version": "2.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "LightClientGradle-2.1.2-SNAPSHOT.jar",
          "url": "LightClientGradle-2.1.2-SNAPSHOT.jar",
          "size": 175073,
          "sha512": "b16f6e01955aff78a0ddbf2fa1f319f8857c2d3929910ce5f7bebeb505ac43e2bef8cb8aa70b08b02473a72203d194da837e2a56db704d9008ba33535285ed01",
          "sha256": "9cd4a72532a2417144bd3940d264d7ee8f9a2f64f023cf2ead853782c71c1cab",
          "sha1": "2b8b1aa7b03c377c3beefbc73d13c244e081e165",
          "md5": "bb78f95a58fb94b361456bf4134a1793"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "com.github.FabricMc",
          "module": "mapping-io",
          "version": {
            "requires": "597f0722d6"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.zeroturnaround",
          "module": "zt-zip",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "quiltflower",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "stitch",
          "version": {
            "requires": "0.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "enigma"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "LightClientGradle-2.1.2-SNAPSHOT.jar",
          "url": "LightClientGradle-2.1.2-SNAPSHOT.jar",
          "size": 175073,
          "sha512": "b16f6e01955aff78a0ddbf2fa1f319f8857c2d3929910ce5f7bebeb505ac43e2bef8cb8aa70b08b02473a72203d194da837e2a56db704d9008ba33535285ed01",
          "sha256": "9cd4a72532a2417144bd3940d264d7ee8f9a2f64f023cf2ead853782c71c1cab",
          "sha1": "2b8b1aa7b03c377c3beefbc73d13c244e081e165",
          "md5": "bb78f95a58fb94b361456bf4134a1793"
        }
      ]
    }
  ]
}
