{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nickacpt.lightclient",
    "module": "LightClientGradle",
    "version": "2.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "LightClientGradle-2.0.8-SNAPSHOT.jar",
          "url": "LightClientGradle-2.0.8-SNAPSHOT.jar",
          "size": 173331,
          "sha512": "9d1abca200da3c268f8a945628913975deb0fd987a6c0113c1b0d5ea24aba4a0affbdad3bcbdb95727a7d9bf7cb2476c1220562cd532eda26f77e13f082c98c4",
          "sha256": "8446507e9df4d8086574d378b56d4a451ffe73f14bf20c9ef21eff79ed431b7b",
          "sha1": "9bf8c4e9fb7a2064eccc0c26bda1bb2507b3a721",
          "md5": "79366a602e0dfd6a8166327bb103f3e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "com.github.FabricMc",
          "module": "mapping-io",
          "version": {
            "requires": "597f0722d6"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.zeroturnaround",
          "module": "zt-zip",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "quiltflower",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "stitch",
          "version": {
            "requires": "0.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "enigma"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "LightClientGradle-2.0.8-SNAPSHOT.jar",
          "url": "LightClientGradle-2.0.8-SNAPSHOT.jar",
          "size": 173331,
          "sha512": "9d1abca200da3c268f8a945628913975deb0fd987a6c0113c1b0d5ea24aba4a0affbdad3bcbdb95727a7d9bf7cb2476c1220562cd532eda26f77e13f082c98c4",
          "sha256": "8446507e9df4d8086574d378b56d4a451ffe73f14bf20c9ef21eff79ed431b7b",
          "sha1": "9bf8c4e9fb7a2064eccc0c26bda1bb2507b3a721",
          "md5": "79366a602e0dfd6a8166327bb103f3e4"
        }
      ]
    }
  ]
}
