{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nickacpt.lightclient",
    "module": "LightClientGradle",
    "version": "1.3.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "LightClientGradle-1.3.5-SNAPSHOT.jar",
          "url": "LightClientGradle-1.3.5-SNAPSHOT.jar",
          "size": 173361,
          "sha512": "46806943002fcd3fc69c75a1e096481d7d2edad7797a645217a911d72cd4274a5fc10332e6a5a1a069ada0b7295c6ce4077d3e8d3ed8a10eeab06070f839e495",
          "sha256": "60d525db16da9eb893aa79ae190c96b5cf8bf7b4d3c4dd6b3740963fbeb2b352",
          "sha1": "9f621cdb843abfc10f14fb0315a6b03dbbed5f5d",
          "md5": "fa7c72e6186f47985cb4c0d4db28161b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "com.github.FabricMc",
          "module": "mapping-io",
          "version": {
            "requires": "5879155d42"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.4"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.zeroturnaround",
          "module": "zt-zip",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "quiltflower",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "stitch",
          "version": {
            "requires": "0.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "enigma"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "LightClientGradle-1.3.5-SNAPSHOT.jar",
          "url": "LightClientGradle-1.3.5-SNAPSHOT.jar",
          "size": 173361,
          "sha512": "46806943002fcd3fc69c75a1e096481d7d2edad7797a645217a911d72cd4274a5fc10332e6a5a1a069ada0b7295c6ce4077d3e8d3ed8a10eeab06070f839e495",
          "sha256": "60d525db16da9eb893aa79ae190c96b5cf8bf7b4d3c4dd6b3740963fbeb2b352",
          "sha1": "9f621cdb843abfc10f14fb0315a6b03dbbed5f5d",
          "md5": "fa7c72e6186f47985cb4c0d4db28161b"
        }
      ]
    }
  ]
}
