{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nickacpt.lightclient",
    "module": "LightClientGradle",
    "version": "1.3.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "LightClientGradle-1.3.4-SNAPSHOT.jar",
          "url": "LightClientGradle-1.3.4-SNAPSHOT.jar",
          "size": 172221,
          "sha512": "033175c6f46b73462c52a79be2774eabf70a7091c864b7d0454d12810cd38da7846a31053b02ad3bb53081cab6cc2d058ad96a66e574e0ca7af373a4c773f3e7",
          "sha256": "7ec4053256962b43a3abc11e7f8e80ab41f80d02cfe935b6a4acbf40c5963609",
          "sha1": "f732131a88153e93e57e3140ca6099bc513cdf41",
          "md5": "0517c655276f783d4d20a4b803e10703"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "com.github.FabricMc",
          "module": "mapping-io",
          "version": {
            "requires": "5879155d42"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.4"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.zeroturnaround",
          "module": "zt-zip",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "quiltflower",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "stitch",
          "version": {
            "requires": "0.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "enigma"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "LightClientGradle-1.3.4-SNAPSHOT.jar",
          "url": "LightClientGradle-1.3.4-SNAPSHOT.jar",
          "size": 172221,
          "sha512": "033175c6f46b73462c52a79be2774eabf70a7091c864b7d0454d12810cd38da7846a31053b02ad3bb53081cab6cc2d058ad96a66e574e0ca7af373a4c773f3e7",
          "sha256": "7ec4053256962b43a3abc11e7f8e80ab41f80d02cfe935b6a4acbf40c5963609",
          "sha1": "f732131a88153e93e57e3140ca6099bc513cdf41",
          "md5": "0517c655276f783d4d20a4b803e10703"
        }
      ]
    }
  ]
}
