{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nickacpt.lightclient",
    "module": "LightClientGradle",
    "version": "1.3.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "LightClientGradle-1.3.3-SNAPSHOT.jar",
          "url": "LightClientGradle-1.3.3-SNAPSHOT.jar",
          "size": 171972,
          "sha512": "14c000c1674c49bee12d3c7e68a17611e9a6653c29e7e3445781e630f11ce949380f171fb3553ffc79952a162e35644cc63f1a01a158f840533b31999189d7a5",
          "sha256": "931cea636a6b8f46772a4564b136f11fafc02fdaddb10f2b661c3f982ae3bd58",
          "sha1": "0e8a59746fee9a32f2bdca42c2ed25574b77427e",
          "md5": "a341070051da5d92c09e4ac558d035a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "com.github.FabricMc",
          "module": "mapping-io",
          "version": {
            "requires": "5879155d42"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.4"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.zeroturnaround",
          "module": "zt-zip",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "quiltflower",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "stitch",
          "version": {
            "requires": "0.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "enigma"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "LightClientGradle-1.3.3-SNAPSHOT.jar",
          "url": "LightClientGradle-1.3.3-SNAPSHOT.jar",
          "size": 171972,
          "sha512": "14c000c1674c49bee12d3c7e68a17611e9a6653c29e7e3445781e630f11ce949380f171fb3553ffc79952a162e35644cc63f1a01a158f840533b31999189d7a5",
          "sha256": "931cea636a6b8f46772a4564b136f11fafc02fdaddb10f2b661c3f982ae3bd58",
          "sha1": "0e8a59746fee9a32f2bdca42c2ed25574b77427e",
          "md5": "a341070051da5d92c09e4ac558d035a7"
        }
      ]
    }
  ]
}
