{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nickacpt.lightclient",
    "module": "LightClientGradle",
    "version": "2.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "LightClientGradle-2.0.3-SNAPSHOT.jar",
          "url": "LightClientGradle-2.0.3-SNAPSHOT.jar",
          "size": 172949,
          "sha512": "3c55232f759982f82b62268c2d1b7dbaa0db8fcfc240c96b0860f2a67c86885839b4b94f6351772771816ec1c0e1e6ad00af6bdc00542307f6e3b9e15ad17202",
          "sha256": "215533c5d0ece49d03c08dae7325b20a0a4124ba93b6c43a76526c30a0f3623b",
          "sha1": "698cda958e4fe33cade86c4fb8e29ba491c02ec2",
          "md5": "657ebc9af753b781030a1c30b35d141f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "com.github.FabricMc",
          "module": "mapping-io",
          "version": {
            "requires": "597f0722d6"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.zeroturnaround",
          "module": "zt-zip",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "quiltflower",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "stitch",
          "version": {
            "requires": "0.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "enigma"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "LightClientGradle-2.0.3-SNAPSHOT.jar",
          "url": "LightClientGradle-2.0.3-SNAPSHOT.jar",
          "size": 172949,
          "sha512": "3c55232f759982f82b62268c2d1b7dbaa0db8fcfc240c96b0860f2a67c86885839b4b94f6351772771816ec1c0e1e6ad00af6bdc00542307f6e3b9e15ad17202",
          "sha256": "215533c5d0ece49d03c08dae7325b20a0a4124ba93b6c43a76526c30a0f3623b",
          "sha1": "698cda958e4fe33cade86c4fb8e29ba491c02ec2",
          "md5": "657ebc9af753b781030a1c30b35d141f"
        }
      ]
    }
  ]
}
