{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nickacpt.lightclient",
    "module": "LightClientGradle",
    "version": "2.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "LightClientGradle-2.0.1-SNAPSHOT.jar",
          "url": "LightClientGradle-2.0.1-SNAPSHOT.jar",
          "size": 172952,
          "sha512": "68cf21f83f3672312f32466145f58aeade44c06a2d14b1bbd46cc7f3682ab295d16cb0314ef3e61443b06cdc7d39774b077ec7952c3140a549fa2c6905b33170",
          "sha256": "1a366acf38c6bbdcc28e59d57f9d70d1746554715a7a9d95a4dec3c90c8f4284",
          "sha1": "ae662b1b07e71d6e99697bb8342a54b34f764ff5",
          "md5": "84fc3373f4bc6bc08b98829d8abb4060"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "com.github.FabricMc",
          "module": "mapping-io",
          "version": {
            "requires": "597f0722d6"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.zeroturnaround",
          "module": "zt-zip",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "quiltflower",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "stitch",
          "version": {
            "requires": "0.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "enigma"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "LightClientGradle-2.0.1-SNAPSHOT.jar",
          "url": "LightClientGradle-2.0.1-SNAPSHOT.jar",
          "size": 172952,
          "sha512": "68cf21f83f3672312f32466145f58aeade44c06a2d14b1bbd46cc7f3682ab295d16cb0314ef3e61443b06cdc7d39774b077ec7952c3140a549fa2c6905b33170",
          "sha256": "1a366acf38c6bbdcc28e59d57f9d70d1746554715a7a9d95a4dec3c90c8f4284",
          "sha1": "ae662b1b07e71d6e99697bb8342a54b34f764ff5",
          "md5": "84fc3373f4bc6bc08b98829d8abb4060"
        }
      ]
    }
  ]
}
