{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nickacpt.lightclient",
    "module": "LightClientGradle",
    "version": "2.1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "LightClientGradle-2.1.3-SNAPSHOT.jar",
          "url": "LightClientGradle-2.1.3-SNAPSHOT.jar",
          "size": 175169,
          "sha512": "30464afbc76a4e8d391e010e9a9a998b36b9ffe92d7ce83f7aa1aeac27627edae090ef8e37b105c1f1200cbb9a47c54ec9ac34f12ef504d6ba9b310f442d19f6",
          "sha256": "30e8273c35ac37e6a8aeca255712b50e5d51ce5380eff7d6b6138c4bae010985",
          "sha1": "e0576cdc51c002eb54f30318b7669baad7a13f00",
          "md5": "7081f9e2847f90e57986d5e108e72405"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "com.github.FabricMc",
          "module": "mapping-io",
          "version": {
            "requires": "597f0722d6"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.zeroturnaround",
          "module": "zt-zip",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "quiltflower",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "stitch",
          "version": {
            "requires": "0.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "enigma"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "LightClientGradle-2.1.3-SNAPSHOT.jar",
          "url": "LightClientGradle-2.1.3-SNAPSHOT.jar",
          "size": 175169,
          "sha512": "30464afbc76a4e8d391e010e9a9a998b36b9ffe92d7ce83f7aa1aeac27627edae090ef8e37b105c1f1200cbb9a47c54ec9ac34f12ef504d6ba9b310f442d19f6",
          "sha256": "30e8273c35ac37e6a8aeca255712b50e5d51ce5380eff7d6b6138c4bae010985",
          "sha1": "e0576cdc51c002eb54f30318b7669baad7a13f00",
          "md5": "7081f9e2847f90e57986d5e108e72405"
        }
      ]
    }
  ]
}
