{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nickacpt.lightclient",
    "module": "LightClientGradle",
    "version": "1.3.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "LightClientGradle-1.3.6-SNAPSHOT.jar",
          "url": "LightClientGradle-1.3.6-SNAPSHOT.jar",
          "size": 173378,
          "sha512": "a4114bbe8f718c5082844f7882a6be327ffa0a187e72ec2bf07da8fe2019ab4b92958679bfd85fabbf046a4a3887a4e383ef30f289672616af5f32433fa53087",
          "sha256": "cd57b79b246cae7df0e225bc7519caa75908a0e8f7818d487effb20d1f19739f",
          "sha1": "4c49061c439af9969cd5e97274fb793e69bc5760",
          "md5": "60895704d4cc81b8aadb7c26177e87f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "com.github.FabricMc",
          "module": "mapping-io",
          "version": {
            "requires": "5879155d42"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.4"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.zeroturnaround",
          "module": "zt-zip",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "quiltflower",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "stitch",
          "version": {
            "requires": "0.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "enigma"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "LightClientGradle-1.3.6-SNAPSHOT.jar",
          "url": "LightClientGradle-1.3.6-SNAPSHOT.jar",
          "size": 173378,
          "sha512": "a4114bbe8f718c5082844f7882a6be327ffa0a187e72ec2bf07da8fe2019ab4b92958679bfd85fabbf046a4a3887a4e383ef30f289672616af5f32433fa53087",
          "sha256": "cd57b79b246cae7df0e225bc7519caa75908a0e8f7818d487effb20d1f19739f",
          "sha1": "4c49061c439af9969cd5e97274fb793e69bc5760",
          "md5": "60895704d4cc81b8aadb7c26177e87f5"
        }
      ]
    }
  ]
}
