{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nickacpt.lightclient",
    "module": "LightClientGradle",
    "version": "1.3.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "LightClientGradle-1.3.2-SNAPSHOT.jar",
          "url": "LightClientGradle-1.3.2-SNAPSHOT.jar",
          "size": 167629,
          "sha512": "0b158c1829356b6156e3ff0194da53868ff40b77fda7eca68a8c1d3311e51988d0aa5c281d78b05e0cef61c8e4393790d9ffc14975c5fdf3af7648f2e029dc1e",
          "sha256": "239eff4b013021f5dddfa31b0db0a0ae95fe598a57e2cb3cb3d5f20fe4fac832",
          "sha1": "9d97a73856836c4db7db85ecdfecf95448d88bbd",
          "md5": "5499ba6e13677c13c45acc3b0f267736"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.github.FabricMc",
          "module": "mapping-io",
          "version": {
            "requires": "5879155d42"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.4"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.zeroturnaround",
          "module": "zt-zip",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "quiltflower",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "stitch",
          "version": {
            "requires": "0.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "enigma"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "LightClientGradle-1.3.2-SNAPSHOT.jar",
          "url": "LightClientGradle-1.3.2-SNAPSHOT.jar",
          "size": 167629,
          "sha512": "0b158c1829356b6156e3ff0194da53868ff40b77fda7eca68a8c1d3311e51988d0aa5c281d78b05e0cef61c8e4393790d9ffc14975c5fdf3af7648f2e029dc1e",
          "sha256": "239eff4b013021f5dddfa31b0db0a0ae95fe598a57e2cb3cb3d5f20fe4fac832",
          "sha1": "9d97a73856836c4db7db85ecdfecf95448d88bbd",
          "md5": "5499ba6e13677c13c45acc3b0f267736"
        }
      ]
    }
  ]
}
