{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nickacpt.lightclient",
    "module": "LightClientGradle",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "LightClientGradle-1.0-SNAPSHOT.jar",
          "url": "LightClientGradle-1.0-SNAPSHOT.jar",
          "size": 157740,
          "sha512": "e0f61b78bb20299340ed4bfd05583576c0d55b3ef9f28f20120c3ca5f54c79422eb7bbdf3326f5ee7c0b7af0ca3b5d510ec8c2112e4ddd0085a395d6bc6b5796",
          "sha256": "3a8b510f22604a658a9729ba18ae7f64e3cafd7b45ae4e816d10d0b9327ec6da",
          "sha1": "ecbf221f9082b5815a04b4ecf9a1eec733a8ec53",
          "md5": "db442f2536219192a5d39da9d4ca0b9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.github.FabricMc",
          "module": "mapping-io",
          "version": {
            "requires": "5879155d42"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.4"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.zeroturnaround",
          "module": "zt-zip",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "quiltflower",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "stitch",
          "version": {
            "requires": "0.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "enigma"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "LightClientGradle-1.0-SNAPSHOT.jar",
          "url": "LightClientGradle-1.0-SNAPSHOT.jar",
          "size": 157740,
          "sha512": "e0f61b78bb20299340ed4bfd05583576c0d55b3ef9f28f20120c3ca5f54c79422eb7bbdf3326f5ee7c0b7af0ca3b5d510ec8c2112e4ddd0085a395d6bc6b5796",
          "sha256": "3a8b510f22604a658a9729ba18ae7f64e3cafd7b45ae4e816d10d0b9327ec6da",
          "sha1": "ecbf221f9082b5815a04b4ecf9a1eec733a8ec53",
          "md5": "db442f2536219192a5d39da9d4ca0b9c"
        }
      ]
    }
  ]
}
