{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nickacpt.lightclient",
    "module": "LightClientGradle",
    "version": "1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "LightClientGradle-1.3-SNAPSHOT.jar",
          "url": "LightClientGradle-1.3-SNAPSHOT.jar",
          "size": 166986,
          "sha512": "6e38bc6f15bea20254376b54083718d96659a3cd3eec690dde2b47250ad502a3256781c2c2841f063d7fff726ce4201186b12f0a7c9200562a4194a290638e2b",
          "sha256": "7f115d16ea8b4e5556e8b9c05fad212cd3527ea0d8ee891225cd1fb44b3c21ab",
          "sha1": "b2e487252e4c457faf124e8ef7b33e4836c995ba",
          "md5": "c1b46efc2456d4ccb54cc9845dd4a245"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.github.FabricMc",
          "module": "mapping-io",
          "version": {
            "requires": "5879155d42"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.4"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.zeroturnaround",
          "module": "zt-zip",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "quiltflower",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "stitch",
          "version": {
            "requires": "0.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "enigma"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "LightClientGradle-1.3-SNAPSHOT.jar",
          "url": "LightClientGradle-1.3-SNAPSHOT.jar",
          "size": 166986,
          "sha512": "6e38bc6f15bea20254376b54083718d96659a3cd3eec690dde2b47250ad502a3256781c2c2841f063d7fff726ce4201186b12f0a7c9200562a4194a290638e2b",
          "sha256": "7f115d16ea8b4e5556e8b9c05fad212cd3527ea0d8ee891225cd1fb44b3c21ab",
          "sha1": "b2e487252e4c457faf124e8ef7b33e4836c995ba",
          "md5": "c1b46efc2456d4ccb54cc9845dd4a245"
        }
      ]
    }
  ]
}
