{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nickacpt.patchify",
    "module": "patchify-cli",
    "version": "2.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "patchify-cli-2.1.0-SNAPSHOT.jar",
          "url": "patchify-cli-2.1.0-SNAPSHOT.jar",
          "size": 14086,
          "sha512": "35f20a79c2a42d0eab1b55db2f6b6e2968091c51effcc0ca8c1bfa12bfde2884d31405427dd79192c3c50c2a1e9b6d5d613b759e654766fd3fbbb3a5beaf662a",
          "sha256": "267893ab0543464ad6388409f111999b9cfa8f81c97712b107282c3bbc1e754d",
          "sha1": "94225bc75684ca8d970a29001e9e342023ca4be8",
          "md5": "ed139660048de073c8fad9b7644a2daf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.github.ajalt.clikt",
          "module": "clikt",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.github.nickacpt.patchify",
          "module": "patchify-core",
          "version": {
            "requires": "2.1.0-SNAPSHOT"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.13.3"
          }
        }
      ],
      "files": [
        {
          "name": "patchify-cli-2.1.0-SNAPSHOT.jar",
          "url": "patchify-cli-2.1.0-SNAPSHOT.jar",
          "size": 14086,
          "sha512": "35f20a79c2a42d0eab1b55db2f6b6e2968091c51effcc0ca8c1bfa12bfde2884d31405427dd79192c3c50c2a1e9b6d5d613b759e654766fd3fbbb3a5beaf662a",
          "sha256": "267893ab0543464ad6388409f111999b9cfa8f81c97712b107282c3bbc1e754d",
          "sha1": "94225bc75684ca8d970a29001e9e342023ca4be8",
          "md5": "ed139660048de073c8fad9b7644a2daf"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "patchify-cli-2.1.0-SNAPSHOT-all.jar",
          "url": "patchify-cli-2.1.0-SNAPSHOT-all.jar",
          "size": 7493770,
          "sha512": "b3259fbe8c0f176e7bfd944d51cc8b8a81a9c5deb2ad2ef735aa60051c0fe6491610056e65cf0fd3442edcf2de1a1f19a5ac07b89de7ee9077769144a75feab0",
          "sha256": "6df966758ec6e5a49365e92d1ca5da5d849537cb4e2eed0bdefe4cd53a0fea98",
          "sha1": "c41dc1075e28e036649429e21ae571047fe20cb1",
          "md5": "fa02f276a4f7e9b8638d6929023aab44"
        }
      ]
    }
  ]
}
