{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nickacpt.lightclient",
    "module": "LightClientGradle",
    "version": "2.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "LightClientGradle-2.0.7-SNAPSHOT.jar",
          "url": "LightClientGradle-2.0.7-SNAPSHOT.jar",
          "size": 173199,
          "sha512": "81a06e6adb99f1b64f0d2795b19fb82e294a4095758393793dc72bdd7610b5a9389d74b41e78f4fded644bb6f50e6edec9b8537e276b1511c35468ed4c751653",
          "sha256": "c979ea51f5ce0ab6fe03bd4cb1ecc9e1ada0b1923ce9cb1f7fd33f5a7c037d29",
          "sha1": "61f0d05a5ddb42e30ca519d851a80643a396d837",
          "md5": "a869c7624f71394f7f452d001f0d3fd5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "com.github.FabricMc",
          "module": "mapping-io",
          "version": {
            "requires": "597f0722d6"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.zeroturnaround",
          "module": "zt-zip",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "quiltflower",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "stitch",
          "version": {
            "requires": "0.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "enigma"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "LightClientGradle-2.0.7-SNAPSHOT.jar",
          "url": "LightClientGradle-2.0.7-SNAPSHOT.jar",
          "size": 173199,
          "sha512": "81a06e6adb99f1b64f0d2795b19fb82e294a4095758393793dc72bdd7610b5a9389d74b41e78f4fded644bb6f50e6edec9b8537e276b1511c35468ed4c751653",
          "sha256": "c979ea51f5ce0ab6fe03bd4cb1ecc9e1ada0b1923ce9cb1f7fd33f5a7c037d29",
          "sha1": "61f0d05a5ddb42e30ca519d851a80643a396d837",
          "md5": "a869c7624f71394f7f452d001f0d3fd5"
        }
      ]
    }
  ]
}
