{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nickacpt.lightclient",
    "module": "LightClientGradle",
    "version": "2.1.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "LightClientGradle-2.1.5-SNAPSHOT.jar",
          "url": "LightClientGradle-2.1.5-SNAPSHOT.jar",
          "size": 177106,
          "sha512": "83720ad63333c1060cbf8bbd6c48e9a9d063157690330583696e606281d5b1e1282619151a0f9164baa36858631bb94275832e8046150ccb4b0b822897506062",
          "sha256": "205cf21bfdf3fd3eb72e0254001dd0a82cd36e8b515fb00016413e085b30b9bf",
          "sha1": "f6d582689831d9322aac7a2f994cfe7441e18c73",
          "md5": "007738e27c97ca2c6abf1e80e221eea3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "com.github.FabricMc",
          "module": "mapping-io",
          "version": {
            "requires": "597f0722d6"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.zeroturnaround",
          "module": "zt-zip",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "quiltflower",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "stitch",
          "version": {
            "requires": "0.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "enigma"
            }
          ]
        },
        {
          "group": "com.github.MCPHackers",
          "module": "RetroDebugInjector",
          "version": {
            "requires": "d5eedc0d3f"
          },
          "excludes": [
            {
              "group": "*",
              "module": "asm"
            },
            {
              "group": "*",
              "module": "mapping-io"
            },
            {
              "group": "*",
              "module": "asm-tree"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "LightClientGradle-2.1.5-SNAPSHOT.jar",
          "url": "LightClientGradle-2.1.5-SNAPSHOT.jar",
          "size": 177106,
          "sha512": "83720ad63333c1060cbf8bbd6c48e9a9d063157690330583696e606281d5b1e1282619151a0f9164baa36858631bb94275832e8046150ccb4b0b822897506062",
          "sha256": "205cf21bfdf3fd3eb72e0254001dd0a82cd36e8b515fb00016413e085b30b9bf",
          "sha1": "f6d582689831d9322aac7a2f994cfe7441e18c73",
          "md5": "007738e27c97ca2c6abf1e80e221eea3"
        }
      ]
    }
  ]
}
