{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nickacpt.lightclient",
    "module": "LightClientGradle",
    "version": "2.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "LightClientGradle-2.0.2-SNAPSHOT.jar",
          "url": "LightClientGradle-2.0.2-SNAPSHOT.jar",
          "size": 172950,
          "sha512": "f7a9fa9d01eb8ab2c454152c61c9a1d3cff7e7ca1c4cc5fdd41cdc689f7b911dd6cad1e27429902dce23ba48e512357ba3442918a8e0b4beda5264c79bcb6bc4",
          "sha256": "b7203fc61f62440560d3e4095d3f10921df6692db6e75ac4036bb6d5fdd4f5c6",
          "sha1": "211877d63acdf5e99150c9d1b9a6239eebd02101",
          "md5": "ee9ad3ee845641a0475394e9c77c1162"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "com.github.FabricMc",
          "module": "mapping-io",
          "version": {
            "requires": "597f0722d6"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.zeroturnaround",
          "module": "zt-zip",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "quiltflower",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "stitch",
          "version": {
            "requires": "0.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "enigma"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "LightClientGradle-2.0.2-SNAPSHOT.jar",
          "url": "LightClientGradle-2.0.2-SNAPSHOT.jar",
          "size": 172950,
          "sha512": "f7a9fa9d01eb8ab2c454152c61c9a1d3cff7e7ca1c4cc5fdd41cdc689f7b911dd6cad1e27429902dce23ba48e512357ba3442918a8e0b4beda5264c79bcb6bc4",
          "sha256": "b7203fc61f62440560d3e4095d3f10921df6692db6e75ac4036bb6d5fdd4f5c6",
          "sha1": "211877d63acdf5e99150c9d1b9a6239eebd02101",
          "md5": "ee9ad3ee845641a0475394e9c77c1162"
        }
      ]
    }
  ]
}
