{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nickacpt.lightclient",
    "module": "LightClientGradle",
    "version": "1.3.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "LightClientGradle-1.3.1-SNAPSHOT.jar",
          "url": "LightClientGradle-1.3.1-SNAPSHOT.jar",
          "size": 167590,
          "sha512": "c137b69f7f851d6e9d5034b1732d9528fbe0d0b93526c053baf2dd4726e6aad29260355a6a1f1d81ed29ec965c77e66f349dd1f685004a18490430d1bab3775c",
          "sha256": "acc5ce9c3614602f60f367a57cc1d4c3ba6ce0d684979ee7bd5e5aa051c5a05b",
          "sha1": "abe8fafaf8736dd8f17fa4882df763430353d321",
          "md5": "892f1868f64f8d8fcbfb11165467d676"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.github.FabricMc",
          "module": "mapping-io",
          "version": {
            "requires": "5879155d42"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.4"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.zeroturnaround",
          "module": "zt-zip",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "quiltflower",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "stitch",
          "version": {
            "requires": "0.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "enigma"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "LightClientGradle-1.3.1-SNAPSHOT.jar",
          "url": "LightClientGradle-1.3.1-SNAPSHOT.jar",
          "size": 167590,
          "sha512": "c137b69f7f851d6e9d5034b1732d9528fbe0d0b93526c053baf2dd4726e6aad29260355a6a1f1d81ed29ec965c77e66f349dd1f685004a18490430d1bab3775c",
          "sha256": "acc5ce9c3614602f60f367a57cc1d4c3ba6ce0d684979ee7bd5e5aa051c5a05b",
          "sha1": "abe8fafaf8736dd8f17fa4882df763430353d321",
          "md5": "892f1868f64f8d8fcbfb11165467d676"
        }
      ]
    }
  ]
}
